site_name: ccn-template
repo_url: https://github.com/flatironinstitute/ccn-template

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    features:
      - navigation.tabs
plugins:
  - search  # make sure the search plugin is still enabled
  - mkdocstrings
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
        nav_file: docs/SUMMARY.md
  - section-index
  - gallery:
      examples_dirs: docs/examples          # path to your example scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
  #     # ... (other options)
nav:
    - Home: index.md
    - Tutorials: generated/gallery
    - Contributing: CONTRIBUTING.md
    - Code References: reference/
    - About: about.md