name: ci
on:
  push:
    - folder_struct_and_setup
#  workflow_dispatch:
#  schedule:
#  - cron: 0 0 1 * 0     # monthly
#  pull_request:
#    branches:
#    - main
#    - development

jobs:
  tox:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.8','3.9', '3.10' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          # using the --upgrade and --upgrade-strategy eager flags ensures that
          # pip will always install the latest allowed version of all
          # dependencies, to make sure the cache doesn't go stale
          pip install --upgrade --upgrade-strategy eager .
          pip install tox
      - name: run tox
        run: |
          run tox -e py # run rox on specified python version

  check:
    if: always()
    needs:
    - tox
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all tests and notebooks succeeded
      uses: re-actors/alls-green@afee1c1eac2a506084c274e9c02c8e0687b48d9e # v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
