name: connect

on:
  push:
    branches:
      - debug_logspace

permissions:
  id-token: write
  contents: read
  actions: read
# added token to secrets
jobs:
  connect:
    name: connect
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH server for Actor
        uses: alexellis/setup-sshd-actor@master
      - name: Connect to activated SSH gateway
        uses: alexellis/actuated-ssh-gateway-action@master
        with:
          gatewayaddr: ${{ secrets.SSH_GATEWAY_IP }}
          secure: true
      - name: Setup a blocking tmux session
        uses: alexellis/block-with-tmux-action@master